### ISSUE TITLE
update the save_grade_and_comment_for_submission method in grades_controller.rb

### ISSUE THREAD

**Issue by jphulse** [jphulse/Program_3_E2470#11]
Sub-Issue of #2 for easier division of work, please see that issue for description.

This issue is focused on the save_grade_and_comment_for_submission  method in the grades_cointroller.

**Comment by Charlie-Eastin** [comment]
Should be able to separate this into two methods save_grade and comment_for_submission

**Comment by Maverick-Middleton** [comment]
Deemed obsolete and removed from the class. Update method will handle everything.
