### ISSUE TITLE
refactor the redirect_when_disallowed method in grades_controller.rb

### ISSUE THREAD

**Issue by jphulse** [jphulse/Program_3_E2470#14]
Sub-Issue of #2 for easier division of work, please see that issue for description.

This issue is focused on the redirect_when_disallowed  method in the grades_cointroller.

**Comment by Charlie-Eastin** [comment]
This can likely be separated into two methods one for redirecting and one for checking if the action is allowed

**Comment by Maverick-Middleton** [comment]
Deemed obsolete and removed from the class.
